ethernet_auth/urls.py
from django.conf.urls import url

from .views import SwitchPortView
from .views import SwitchPortDetailView
from .views import SwitchPortActionCreateView

app_name = 'ethernet_auth'

urlpatterns = [
    url(r'^switches/ports/$', SwitchPortView.as_view(), name='switch_port_list'),
    url(r'^switches/ports/(?P<pk>[0-9]+)/$', SwitchPortDetailView.as_view(), name='switch_port_detail'),
    url(r'^switches/ports/(?P<pk>[0-9]+)/actions/add/$', SwitchPortActionCreateView.as_view(),
        name='switch_port_action_create')
]

members/urls.py
from django.conf.urls import include, url
from django.contrib import admin

from network.views import device
from members.views import legal_view

urlpatterns = [
    url(r'^legal$', legal_view, name="legal"),
    url(r'^admin/', admin.site.urls),
    url(
        r'^accounts/',
        include('accounts.urls', namespace='accounts'),
    ),
    url(r'^captcha/', include('captcha.urls')),
    url(r'^network/', include('network.urls')),
    url(r'^cleaning/', include('cleaning.urls')),
    url(r'^ethernet/', include('ethernet_auth.urls')),
    url(r'^$', device.DeviceView.as_view(), name="portal")
]

network/urls.py
from django.conf.urls import url

from .views import device, interface, render

app_name = 'network'

urlpatterns = [
    url(r'^devices/$',
        device.DeviceView.as_view(),
        name='index'),
    url(r'^devices/add/$',
        device.DeviceCreateView.as_view(),
        name='device_create'),
    url(r'^devices/(?P<pk>[0-9]+)/$',
        device.DeviceDetailView.as_view(),
        name='device_detail'),
    url(r'^devices/(?P<pk>[0-9]+)/edit/$',
        device.DeviceUpdateView.as_view(),
        name='device_update'),
    url(r'^devices/(?P<pk>[0-9]+)/delete/$',
        device.DeviceDeleteView.as_view(),
        name='device_delete'),

    url(r'^devices/(?P<pk>[0-9]+)/interfaces/add/$',
        interface.InterfaceCreateView.as_view(),
        name='interface_create'),
    url(r'^devices/(?P<pk1>[0-9]+)/interfaces/(?P<pk2>[0-9]+)/edit/$',
        interface.InterfaceUpdateView.as_view(),
        name='interface_update'),
    url(r'^devices/(?P<pk1>[0-9]+)/interfaces/(?P<pk2>[0-9]+)/delete/$',
        interface.InterfaceDeleteView.as_view(),
        name='interface_delete'),

    url(r'^render/dhcp/$',
        render.RenderDHCPView.as_view(),
        name='render_DHCP'),
    url(r'^render/dns/$',
        render.RenderDNSView.as_view(),
        name='render_DNS'),
    url(r'^render/dns/reverse/$',
        render.RenderReverseDNSView.as_view(),
        name='render_reverse_DNS'),
]

network/models.py
from django.db import models
from django.core.validators import RegexValidator
from django.core.exceptions import ValidationError
from django.core.urlresolvers import reverse
from django.contrib.auth.models import User
from django.conf import settings

""" Constants for interface type """

WIFI = "WLP"
ETHERNET = "ETH"
INTERFACE_TYPE_CHOICES = (
    (WIFI, "Wifi"),
    (ETHERNET, "Ethernet")
)

""" Generates a new IP address for the device """


def get_new_IP_address():
    def lastMember(device):
        return int(device.device_ip.split(".")[3])

    used_members = list(map(lastMember, Device.objects.all()))
    available_IPs = ([a for a in range(settings.IP_RANGE_START,
                                       settings.IP_RANGE_END)
                      if a not in used_members])

    if len(available_IPs) == 0:
        raise ValidationError("No more available IPs !")
    return settings.IP_NETWORK_PREFIX + str(available_IPs[0])

""" Models definition """


class Device(models.Model):

    user = models.ForeignKey(User, on_delete=models.CASCADE)

    """ Only accept a device name composed of alphanumeric characters
    and - and _ """
    device_name = models.CharField(
            max_length=25,
            validators=[RegexValidator(
                regex="^[a-zA-Z0-9_−]{1,25}$",
                message="Invalid name")])

    device_ip = models.GenericIPAddressField(
            protocol="IPv4",
            unique=True)

    description = models.CharField(
            max_length=255,
            blank=True)

    add_date = models.DateTimeField(
            "Date added",
            auto_now_add=True)

    last_modified = models.DateTimeField(
            "Last update",
            auto_now=True)

    """ Check if the user has not another device with the same name, then assign
    a new IP address if needed """
    def clean(self):
        if ((self.user_id is not None)
            and (self.device_name
                 in [d.device_name for d in self.user.device_set.all()
                     if d.id != self.id])):
                raise ValidationError('Device name aleready taken')
        if (self.device_ip is None):
            self.device_ip = get_new_IP_address()
        return super(Device, self).clean()

    def save(self, *args, **kwargs):
        if (self.user.device_set.all().count()
            >= settings.MAX_DEVICE_PER_USER):
            raise ValidationError('Too much devices')
        return super(Device, self).save(*args, **kwargs)

    def __str__(self):
        return self.device_name + " (" + self.description + ")"

    def get_absolute_url(self):
        return reverse('network:device_detail', kwargs={'pk': self.pk})

    def get_FQDN(self):
        return self.device_name + "." + self.user.username + "." + DNS_DOMAIN

    def get_last_ip_block(self):
        return int(self.device_ip.split(".")[3])

    class Meta:
        permissions = (
            ("can_publish_device", "Can use this device on the network"),
        )


class Interface(models.Model):
    device = models.ForeignKey(Device, on_delete=models.CASCADE)

    interface_type = models.CharField(
            max_length=3,
            choices=INTERFACE_TYPE_CHOICES,
            default=ETHERNET)

    mac_address = models.CharField(
            max_length=17,
            validators=[RegexValidator(
                regex="^([0-9A-Fa-f]{2}:){5}([0-9A-Fa-f]{2})$",
                message="Invalid MAC address")],
            unique=True)

    description = models.CharField(
            max_length=255,
            blank=True)

    add_date = models.DateTimeField(
            "Date added",
            auto_now_add=True)

    last_modified = models.DateTimeField(
            "Last update",
            auto_now=True)

    def save(self, *args, **kwargs):
        if (self.device.interface_set.all().count()
            >= settings.MAX_INTERFACE_PER_DEVICE):
            raise ValidationError('Too much interfaces')
        return super(Interface, self).save(*args, **kwargs)

    def __str__(self):
        return (self.mac_address + " - " + self.interface_type
                + " (" + self.description + ")")

    def get_absolute_url(self):
        return reverse('network:device_detail', kwargs={'pk': self.device.pk})

network/models/interface.py
from django.conf import settings
from django.core.exceptions import ValidationError
from django.core.urlresolvers import reverse
from django.core.validators import RegexValidator
from django.db import models

from .device import Device


# Constants for interface type
WIFI = 'WLP'
ETHERNET = 'ETH'
INTERFACE_TYPE_CHOICES = (
    (WIFI, 'Wifi'),
    (ETHERNET, 'Ethernet'),
)


class Interface(models.Model):
    device = models.ForeignKey(Device, on_delete=models.CASCADE)

    interface_type = models.CharField(
        max_length=3,
        choices=INTERFACE_TYPE_CHOICES,
        default=ETHERNET,
    )

    mac_address = models.CharField(
        max_length=17,
        validators=[
            RegexValidator(
                regex='^([0-9A-Fa-f]{2}:){5}([0-9A-Fa-f]{2})$',
                message="L'addresse mac doit être du format xx:xx:xx:xx:xx:xx,"
                        "et ne doit comprendre que des caractères dans 1-9 et"
                        "a-f"
            )
        ],
        unique=True,
    )

    description = models.CharField(
        max_length=255,
        blank=True,
    )

    add_date = models.DateTimeField(
        'Date added',
        auto_now_add=True,
    )

    last_modified = models.DateTimeField(
        'Last update',
        auto_now=True,
    )

    def save(self, *args, **kwargs):
        interface_count = self.device.interface_set.all().count()
        if interface_count >= settings.MAX_INTERFACE_PER_DEVICE:
            raise ValidationError('Too many interfaces')
        return super(Interface, self).save(*args, **kwargs)

    def __str__(self):
        return '{mac} - {interface_type} ({description})'.format(
            mac=self.mac_address,
            interface_type=self.interface_type,
            description=self.description,
        )

    def get_absolute_url(self):
        return reverse('network:device_detail', kwargs={'pk': self.device.pk})

network/forms/device.py
from django.forms import ModelForm
from django.forms import TextInput
from ..models.device import Device


class DeviceForm(ModelForm):
    class Meta:
        model = Device
        fields = ['device_name', 'description']
        widgets = {
            'device_name': TextInput(attrs={
                'pattern': '[-a-zA-Z0-9]{1,25}$',
                'placeholder': 'Caractères alphanumériques et "-"',
            }),
        }

network/forms/interface.py
from django import forms

from ..models.interface import (
    Interface,
    INTERFACE_TYPE_CHOICES,
)


class InterfaceForm(forms.ModelForm):
    '''Form declaration for the interface model.'''
    interface_type = forms.ChoiceField(choices=INTERFACE_TYPE_CHOICES)

    class Meta:
        model = Interface
        fields = ['interface_type', 'mac_address', 'description']
        widgets = {
                'mac_address': forms.TextInput(
                    attrs={
                        'pattern': '^([0-9A-Fa-f]{2}:){5}([0-9A-Fa-f]{2})$',
                        'placeholder': '12:56:90:ab:cd:ef'
                    }
                ),
        }

network/views/device.py
'''Views for the device model.'''
from django.contrib.auth.mixins import LoginRequiredMixin
from django.core.exceptions import ValidationError
from django.core.urlresolvers import reverse_lazy
from django.shortcuts import get_object_or_404
from django.views import generic

from ..forms.device import DeviceForm
from ..models.device import Device


class DeviceView(LoginRequiredMixin, generic.ListView):
    template_name = 'network/devices.html'
    context_object_name = 'user_devices_list'

    def get_queryset(self):
        return Device.objects.filter(user=self.request.user)


class DeviceDetailView(LoginRequiredMixin, generic.DetailView):
    model = Device

    def get_object(self, queryset=None):
        return get_object_or_404(
            Device,
            pk=self.kwargs['pk'],
            user=self.request.user,
        )


class DeviceCreateView(LoginRequiredMixin, generic.edit.CreateView):
    '''Add the current user as device owner.'''
    form_class = DeviceForm
    model = Device

    def form_valid(self, form):
        device = form.save(commit=False)
        device.user = self.request.user

        try:
            device.full_clean()
        except ValidationError as e:
            form.add_error('device_name', str(e))
            return super(DeviceCreateView, self).form_invalid(form)

        return super(DeviceCreateView, self).form_valid(form)


class DeviceUpdateView(LoginRequiredMixin, generic.edit.UpdateView):
    success_url = reverse_lazy('network:index')
    fields = ['device_name', 'description']

    def get_object(self, queryset=None):
        return get_object_or_404(
            Device,
            pk=self.kwargs['pk'],
            user=self.request.user,
        )


class DeviceDeleteView(LoginRequiredMixin, generic.edit.DeleteView):
    success_url = reverse_lazy('network:index')
    model = Device

    def get_object(self, queryset=None):
        return get_object_or_404(
            Device,
            pk=self.kwargs['pk'],
            user=self.request.user,
        )

network/views/interface.py
from django.contrib.auth.mixins import LoginRequiredMixin
from django.core.urlresolvers import reverse_lazy
from django.shortcuts import get_object_or_404
from django.views import generic

from ..forms.interface import InterfaceForm
from ..models.device import Device
from ..models.interface import Interface


def get_interface(kwargs, request, queryset=None):
    device = get_object_or_404(
        Device,
        pk=kwargs['pk1'],
        user=request.user,
    )

    return get_object_or_404(
        Interface,
        pk=kwargs['pk2'],
        device=device,
    )


# Views for the interface model

class InterfaceCreateView(generic.edit.CreateView):
    '''Add the device referenced in url as the interface owner.'''

    model = Interface
    form_class = InterfaceForm

    def form_valid(self, form):
        interface = form.save(commit=False)
        device = get_object_or_404(
            Device,
            pk=self.kwargs['pk'],
            user=self.request.user,
        )

        interface.device = device
        interface.full_clean()

        return super(InterfaceCreateView, self).form_valid(form)


class InterfaceUpdateView(LoginRequiredMixin, generic.edit.UpdateView):
    success_url = reverse_lazy('network:index')
    form_class = InterfaceForm

    def get_object(self, queryset=None):
        return get_interface(self.kwargs, self.request, queryset=None)


class InterfaceDeleteView(LoginRequiredMixin, generic.edit.DeleteView):
    success_url = reverse_lazy('network:index')
    model = Interface

    def get_object(self, queryset=None):
        return get_interface(self.kwargs, self.request, queryset=None)

network/views/render.py
import time

from os import remove
from os.path import exists

from django.conf import settings
from django.contrib.auth.models import User
from django.db.models import Q
from django.http import HttpResponse
from django.template import loader
from django.views import generic

from ..models.device import Device
from ..models.interface import Interface


class RenderView(generic.base.View):
    ''' This class allows direct template rendering into a file.
    It is used to generate network configuration files for DNS and
    DHCP servers.
    All the necessary application configuration settings are loaded in
    the template context with get_config_dict. This function also generates
    the serial for the DNS configurations'''

    # Useful functions
    def users_with_perm(self, perm_name):
        return User.objects.filter(
            Q(is_superuser=True) |
            Q(user_permissions__codename=perm_name) |
            Q(groups__permissions__codename=perm_name)
        ).distinct()

    def get_interfaces(self):
        return Interface.objects.filter(
            device__user__in=self.users_with_perm('can_publish_device'),
        )

    def get_devices(self):
        return Device.objects.filter(
            user__in=self.users_with_perm('can_publish_device'),
        )

    def get_config_dict(self):
        '''Loads config options into a dictionnary for template context.'''
        return {
            'TTL': settings.TTL,
            'NEGATIVE_CACHE_TTL': settings.NEGATIVE_CACHE_TTL,
            'REFRESH': settings.REFRESH,
            'RETRY': settings.RETRY,
            'EXPIRE': settings.EXPIRE,
            'SERIAL': settings.DNS_BASE_SERIAL + int(time.time() / 100),
            'DNS_DOMAIN': settings.DNS_DOMAIN,
            'REV_DNS_DOMAIN': settings.REV_DNS_DOMAIN,
            'DNS_DOMAIN_SEARCH': settings.DNS_DOMAIN_SEARCH,
            'DNS_SERVER_1': settings.DNS_SERVER_1,
            'DNS_SERVER_2': settings.DNS_SERVER_2,
            'REV_DNS_ORIGIN': settings.REV_DNS_ORIGIN,
            'DOMAIN_ROOT_SERVER': settings.DOMAIN_ROOT_SERVER,
            'DOMAIN_MAIL_SERVER': settings.DOMAIN_MAIL_SERVER,
        }

    def render_file(self, request, template, object_list, output_path):
        ''' Render the given template into the output_path using a context
        made of object_list and get_config_dict return value'''

        template = loader.get_template(template)

        context = self.get_config_dict()
        context['object_list'] = object_list

        with open(output_path, 'w') as output:
            output.write(template.render(context, request))


# Config rendering views

class RenderDHCPView(RenderView):
    ''' Generate a DHCP configuration file with the interfaces registered in
    the application '''
    def get(self, request, *args, **kwargs):
        if exists(settings.DHCP_CONFIG_OUTPUT):
            remove(settings.DHCP_CONFIG_OUTPUT)

        interface_list = self.get_interfaces()
        self.render_file(
            request,
            'network/render_dhcp.conf',
            interface_list,
            settings.DHCP_CONFIG_OUTPUT,
        )

        return HttpResponse('OK')


class RenderDNSView(RenderView):
    ''' Generate a DNS configuration file (serial derived from timestamp) '''
    def get(self, request, *args, **kwargs):
        if exists(settings.DNS_CONFIG_OUTPUT):
            remove(settings.DNS_CONFIG_OUTPUT)

        device_list = self.get_devices()
        self.render_file(
            request,
            'network/render_dns.conf',
            device_list,
            settings.DNS_CONFIG_OUTPUT,
        )

        return HttpResponse('OK')


class RenderReverseDNSView(RenderView):
    ''' Generate a reverse DNS configuration file (serial derived from
    timestamp) '''
    def get(self, request, *args, **kwargs):
        if exists(settings.REV_DNS_CONFIG_OUTPUT):
            remove(settings.REV_DNS_CONFIG_OUTPUT)

        device_list = self.get_devices()
        self.render_file(
            request,
            'network/render_reverse_dns.conf',
            device_list,
            settings.REV_DNS_CONFIG_OUTPUT,
        )

        return HttpResponse('OK')

network/templates/network/device_confirm_delete.html
{% extends "base_network.html" %}
{% block title %}
Suppression de l’appareil
{% endblock %}

{% block main %}
<form action="" method="post">{% csrf_token %}
	<p>Souhaitez vous vraiment supprimer "{{ object.device_name }}" ?</p>
	<input type="submit" value="Confirmer" class="btn" />
</form>

{% endblock %}

network/templates/network/device_detail.html
{% extends "base_network.html" %}

{% block title %} Appareil: {{ object.device_name }} {% endblock title %}

{% block main %}
<div class="row">
	<ul>
		<li>
			Nom : {{ object.device_name }}
		</li>
		<li>
			Description : {{ device.description }}
		</li>
		<li>
			Adresse IP : {{ device.device_ip }}
		</li>
</div>
<div class="row">
	<h4>Interfaces</h4>
	{% if device.interface_set.all %}
	<table class="highlight bordered">
		<thead>
			<tr>
				<th>
					Type
				</th>
				<th>
					Description
				</th>
				<th>
					Adresse MAC
				</th>
			</tr>
		</thead>
		<tbody>
			{% for interface in device.interface_set.all %}
			<tr>
				<td>
					{{ interface.interface_type }}
				</td>
				<td>
					{{ interface.description }}
				</td>
				<td>
					{{ interface.mac_address }}
				</td>
			</tr>
			{% endfor %}
		</tbody>
	</table>
</div>
<div class="row">
	<a href="{% url "network:device_update" device.id%}"
			class="btn">
		Modifier
	</a>
	{% else %}
		Aucune interface enregistrée,
		<a href="{% url "network:interface_create" device.id %}">
				ajoutez-en une !
		</a>
	{% endif %}
</div>

{% endblock %}

network/templates/network/device_form.html
{% extends "base_network.html" %}
{% block title %}
	{% if object.interface_set.all %}
		Modification d’un appareil
	{% else %}
		Ajout d’un appareil
	{% endif %}
{% endblock %}

{% block main %}
<div class="row">
	<form action="" method="post">
		{% csrf_token %}
		{{ form.as_p }}
		<input type="submit" value="Sauvegarder" class="btn" />
	</form>
</div>

{% if object %}
<hr/>

<div class="row">
	<h4>Interfaces</h4>
	{% if object.interface_set.all %}
		<table class="highlight bordered">
			<thead>
				<tr>
					<th>
						Type
					</th>
					<th>
						Description
					</th>
					<th>
						Adresse MAC
					</th>
					<th colspan=2>
						Options
					</th>
				</tr>
			</thead>
			<tbody>
				{% for interface in object.interface_set.all %}
				<tr>
					<td>
						{{ interface.interface_type }}
					</td>
					<td>
						{{ interface.description }}
					</td>
					<td>
						{{ interface.mac_address }}
					</td>
					<td>
						<a href="{% url "network:interface_update" object.id interface.id %}"
								class="btn">
							Modifier
						</a>
					</td>
					<td>
						<a href="{% url "network:interface_delete" object.id interface.id %}"
								class="btn">
							Supprimer
						</a>
					</td>
				</tr>
				{% endfor %}
			</tbody>
		</table>
	</div>
	<div class="row">
		<a href="{% url "network:interface_create" object.id %}"
				class="btn">Ajouter une interface</a>
	{% else %}
		Aucune interface enregistrée,
		<a href="{% url "network:interface_create" object.id %}">
				ajoutez-en une !
		</a>
	{% endif %}
</div>
{% endif %}

{% endblock %}

network/templates/network/devices.html
{% extends "base_network.html" %}
{% block title %}
	Mes appareils
{% endblock %}

{% block main %}
<div class="row">
	{% if user_devices_list %}
	<table class="highlight bordered">
		<thead>
			<tr>
				<th width="25%">
					Nom
				</th>
				<th width="25%">
					Description
				</th>
				<th>
					Adresse IP
				</th>
				<th>
					Interfaces
				</th>
				<th>
					Options
				</th>
			</tr>
		</thead>
		<tbody>
			{% for device in user_devices_list %}
			<tr>
				<td>
					<a href="{% url "network:device_detail" device.id %}">
						{{ device.device_name }}
					</a>
				</td>
				<td>
					{{ device.description }}
				</td>
				<td>
					{{ device.device_ip }}
				</td>
				<td>
					{{ device.interface_set.count }}
				</td>
				<td>
					<a href="{% url "network:device_detail" device.id %}"
						class="btn">
						Voir
					</a>
					&nbsp;
					<a href="{% url "network:device_delete" device.id %}"
							class="btn">
						Supprimer
					</a>
				</td>
			</tr>
			{% endfor %}
		</tbody>
	</table>
	{% else %}
	<p>Aucun appareil enregistré</p>
	{% endif %}
</div>

<div class="row">
	<a href="{% url "network:device_create" %}" class="btn">
		Ajouter un appareil
	</a>
</div>

{% endblock %}

network/templates/network/interface_confirm_delete.html
{% extends "base_network.html" %}
{% block title %}
	Suppression d’une interface
{% endblock %}


{% block main %}

<form action="" method="post">{% csrf_token %}
	<p>Souhaitez vous vraiment supprimer "{{ object.mac_address }}" ?</p>
	<input type="submit" value="Confirmer" class="btn" />
</form>

{% endblock %}

network/templates/network/interface_form.html
{% extends "base_network.html" %}
{% block title %}
	Interfaces
{% endblock %}

{% block main %}
<form action="" method="post">
	{% csrf_token %}
	{{ form.as_p }}
	<input type="submit" value="Sauvegarder" class="btn" />
</form>
{% endblock %}