ethernet_auth/urls.py
from django.conf.urls import url

from .views import SwitchPortView
from .views import SwitchPortDetailView
from .views import SwitchPortActionCreateView

app_name = 'ethernet_auth'

urlpatterns = [
    url(r'^switches/ports/$', SwitchPortView.as_view(), name='switch_port_list'),
    url(r'^switches/ports/(?P<pk>[0-9]+)/$', SwitchPortDetailView.as_view(), name='switch_port_detail'),
    url(r'^switches/ports/(?P<pk>[0-9]+)/actions/add/$', SwitchPortActionCreateView.as_view(),
        name='switch_port_action_create')
]

members/urls.py
from django.conf.urls import include, url
from django.contrib import admin

from network.views import device
from members.views import legal_view

urlpatterns = [
    url(r'^legal$', legal_view, name="legal"),
    url(r'^admin/', admin.site.urls),
    url(
        r'^accounts/',
        include('accounts.urls', namespace='accounts'),
    ),
    url(r'^captcha/', include('captcha.urls')),
    url(r'^network/', include('network.urls')),
    url(r'^cleaning/', include('cleaning.urls')),
    url(r'^ethernet/', include('ethernet_auth.urls')),
    url(r'^$', device.DeviceView.as_view(), name="portal")
]

ethernet_auth/models.py
'''Model definition for the ethernet authentication application.'''
from django.contrib.auth.models import User
from django.core.exceptions import ValidationError
from django.db import models
from django.utils import timezone

# Constants used to describe a SwitchPort status
AUTO = 'AUTO'
AUTHORIZED = 'AUTHORIZED'
UNAUTHORIZED = 'UNAUTHORIZED'
SWITCH_PORT_STATE = (
    (AUTO, 'Automatique'),
    (AUTHORIZED, 'Ouvert'),
    (UNAUTHORIZED, 'Fermé')
)


class Switch(models.Model):
    '''
    Define a switch that contains ports configured to work with 802.1x authentication.

    Some settings of the switch, such as the username that should be used for telnet connection,
    the password and the telnet adaptater should be defined in the platform configuration.
    '''

    name = models.CharField('Name', max_length=32, unique=True)
    description = models.CharField('Description', max_length=255, blank=True)

    ip_address = models.GenericIPAddressField('IP address', protocol='IPv4', unique=True)

    def __str__(self):
        return '{} - {} ({})'.format(self.name, self.description, self.ip_address)


class SwitchPort(models.Model):
    '''Define a switch port.'''

    switch = models.ForeignKey(Switch, on_delete=models.CASCADE)

    label = models.CharField('Label', max_length=32)
    name = models.CharField('Name', max_length=16)

    default_state = models.CharField('Default state', max_length=12, choices=SWITCH_PORT_STATE, default=AUTO)

    # Though we can get the current state of the switch port using the SwitchPortAction model,
    # this field allows to store the _actual_ value of the switch port (and not the value that can be
    # extrapolated from the SwitchPortAction model).
    #
    # This is useful especially in cases where the switch update fails.
    current_state = models.CharField('Current state', max_length=12, choices=SWITCH_PORT_STATE, default=AUTO)

    last_modified = models.DateTimeField('Last update', auto_now=True)

    def __str__(self):
        return '{} - {} ({})'.format(self.label, self.name, self.switch.name)


class SwitchPortAction(models.Model):
    '''
    Define an action made on a given switch port.

    This model is also responsible for defining expiracy timestamps for actions made on switch ports.
    Note that for each port, only one action should be active at the time.
    '''

    switch_port = models.ForeignKey(SwitchPort, on_delete=models.CASCADE)
    user = models.ForeignKey(User, on_delete=models.CASCADE)

    new_state = models.CharField('New state', max_length=12, choices=SWITCH_PORT_STATE)

    add_date = models.DateTimeField('Date added', auto_now_add=True)
    expiration_date = models.DateTimeField('Expiration date')

    def save(self, *args, **kwargs):
        concurrent_action = SwitchPortAction.objects.filter(switch_port=self.switch_port,
                                                            expiration_date__gt=timezone.now()).first()
        if concurrent_action is not None and concurrent_action != self:
            raise ValidationError('Another action is currently active on this port')

        return super(SwitchPortAction, self).save(*args, **kwargs)

    def __str__(self):
        return '{} - {} ({})'.format(self.switch_port.label, self.user, self.expiration_date)

ethernet_auth/forms.py
from django.forms import ModelForm
from django.forms import SplitDateTimeWidget

from .models import SwitchPortAction


class SwitchPortActionForm(ModelForm):
    class Meta:
        model = SwitchPortAction
        fields = ['new_state', 'expiration_date']
        widgets = {
            'expiration_date': SplitDateTimeWidget()
        }

ethernet_auth/views.py
'''Views for the ethernet authentication application.'''
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib import messages
from django.core.exceptions import ValidationError
from django.core.urlresolvers import reverse_lazy
from django.shortcuts import get_object_or_404
from django.views import generic

from .forms import SwitchPortActionForm
from .models import SwitchPort
from .models import SwitchPortAction


class SwitchPortView(LoginRequiredMixin, generic.ListView):
    template_name = 'ethernet_auth/switchPorts.html'
    context_object_name = 'switch_ports_list'

    def get_queryset(self):
        return SwitchPort.objects.all()


class SwitchPortDetailView(LoginRequiredMixin, generic.DetailView):
    model = SwitchPort


class SwitchPortActionCreateView(LoginRequiredMixin, generic.CreateView):
    form_class = SwitchPortActionForm
    model = SwitchPortAction
    success_url = reverse_lazy('ethernet_auth:switch_port_list')

    def form_valid(self, form):
        action = form.save(commit=False)
        action.user = self.request.user
        action.switch_port = get_object_or_404(SwitchPort, pk=self.kwargs['pk'])

        try:
            action.full_clean()
        except ValidationError as e:
            form.add_error(None, str(e))
            return super(SwitchPortActionCreateView, self).form_invalid(form)

        messages.success(self.request, 'Action enregistrée avec succès.')
        return super(SwitchPortActionCreateView, self).form_valid(form)

ethernet_auth/templates/ethernet_auth/switchPorts.html
{% extends "base_ethernet_auth.html" %}
{% block title %}
	Prises réseau disponibles
{% endblock %}

{% block main %}
<div class="row">
	{% if switch_ports_list %}
	<table class="highlight bordered">
		<thead>
			<tr>
				<th>Nom</th>
				<th>Switch associé</th>
				<th>État par défaut</th>
				<th>État actuel</th>
				<th>Actions</th>
			</tr>
		</thead>
		<tbody>
			{% for switch_port in switch_ports_list %}
			<tr>
				<td>
					<a href="{% url "ethernet_auth:switch_port_detail" switch_port.id %}">
						{{ switch_port.label }}
					</a>
				</td>
				<td>{{ switch_port.switch }}</td>
				<td>{{ switch_port.get_default_state_display }}</td>
				<td>{{ switch_port.get_current_state_display }}</td>
				<td>
					<a href="{% url "ethernet_auth:switch_port_detail" switch_port.id %}" class="btn">
						Voir
					</a>
				</td>
			</tr>
			{% endfor %}
		</tbody>
	</table>
	{% else %}
	<p>Aucune prise réseau disponible</p>
	{% endif %}
</div>

{% endblock %}

ethernet_auth/templates/ethernet_auth/switchport_detail.html
{% extends "base_ethernet_auth.html" %}

{% block title %} Prise {{ object.label }} {% endblock title %}

{% block main %}
<div class="row">
	<ul>
		<li>Nom : {{ object.label }}</li>
		<li>Switch associé : {{ object.switch }}</li>
		<li>État par défaut : {{ object.get_default_state_display }}</li>
		<li>État actuel : {{ object.get_current_state_display }}</li>
</div>
<div class="row">
	<h4>Historique des actions</h4>
	{% if object.switchportaction_set.all %}
	<table class="highlight bordered">
		<thead>
			<tr>
				<th>Créateur</th>
				<th>Nouvel état</th>
				<th>Création</th>
				<th>Expiration</th>
			</tr>
		</thead>
		<tbody>
			{% for action in object.switchportaction_set.all %}
			<tr>
				<td>{{ action.user.first_name }} {{ action.user.last_name }}</td>
				<td>{{ action.get_new_state_display }}</td>
				<td>{{ action.add_date }}</td>
				<td>{{ action.expiration_date }}</td>
			</tr>
			{% endfor %}
		</tbody>
	</table>
	{% else %}
		Aucune action déclarée.
	{% endif %}
</div>
<div class="row">
	<a href="{% url "ethernet_auth:switch_port_action_create" object.id %}" class="btn">Ajouter une action</a>
</div>

{% endblock %}

ethernet_auth/templates/ethernet_auth/switchportaction_form.html
{% extends "base_ethernet_auth.html" %}
{% block title %}
	Ajout d'une action
{% endblock %}

{% block main %}
<div class="row">
	<form action="" method="post">
		{% csrf_token %}
		{{ form.as_p }}
		<input type="submit" value="Valider" class="btn" />
	</form>
</div>

{% endblock %}