accounts/urls.py
from django.conf.urls import url
from django.contrib.auth import views as auth_views
from .views import registration, validation, profile

app_name = "accounts"
urlpatterns = [
    url('^login/$', auth_views.login, name='login'),
    url('^logout/$', auth_views.logout, name='logout'),
    url('^register/$', registration.RegisterView.as_view(), name='register'),
    url('^register/complete/$',
        registration.RegistrationCompleteView.as_view(),
        name='registration-complete'),
    url('^validate/complete/$',
        validation.ValidationCompleteView.as_view(),
        name='validation-complete'),
    url('^validate/token/(?P<token>.*)',
        validation.ValidateRegistrationView.as_view(),
        name='validate'),
    url('^password/update/$',
        profile.UpdatePasswordView.as_view(),
        name='change_password'),
    url('^', profile.ProfileView.as_view(), name='profile'),
]

ethernet_auth/urls.py
from django.conf.urls import url

from .views import SwitchPortView
from .views import SwitchPortDetailView
from .views import SwitchPortActionCreateView

app_name = 'ethernet_auth'

urlpatterns = [
    url(r'^switches/ports/$', SwitchPortView.as_view(), name='switch_port_list'),
    url(r'^switches/ports/(?P<pk>[0-9]+)/$', SwitchPortDetailView.as_view(), name='switch_port_detail'),
    url(r'^switches/ports/(?P<pk>[0-9]+)/actions/add/$', SwitchPortActionCreateView.as_view(),
        name='switch_port_action_create')
]

members/urls.py
from django.conf.urls import include, url
from django.contrib import admin

from network.views import device
from members.views import legal_view

urlpatterns = [
    url(r'^legal$', legal_view, name="legal"),
    url(r'^admin/', admin.site.urls),
    url(
        r'^accounts/',
        include('accounts.urls', namespace='accounts'),
    ),
    url(r'^captcha/', include('captcha.urls')),
    url(r'^network/', include('network.urls')),
    url(r'^cleaning/', include('cleaning.urls')),
    url(r'^ethernet/', include('ethernet_auth.urls')),
    url(r'^$', device.DeviceView.as_view(), name="portal")
]

accounts/models.py
'''Account models definition.'''
import base64
import hashlib
import hmac
import time

from django.contrib.auth.models import User
from django.core.urlresolvers import reverse
from django.db import models


class PendingUser(models.Model):
    username = models.CharField(max_length=10, unique=True)

    first_name = models.CharField('First name', max_length=25)

    last_name = models.CharField('Last name', max_length=25)

    email = models.EmailField('E-Mail', max_length=50, unique=True)

    validation_token = models.CharField('Validation token', max_length=256)

    add_date = models.DateTimeField('Date added', auto_now_add=True)

    last_modified = models.DateTimeField('Last update', auto_now=True)

    def generate_username(self):
        '''Generates a proper username.

        TODO: check if the username is not aleready used in LDAP.'''
        self.username = (
                self.last_name
                + self.first_name
                ).lower().replace(' ', '')[:10]

    def generate_token(self):
        dk = hmac.new(
            bytes(str(time.time()), 'UTF-8'),
            msg=bytes(str(time.time()) + self.email, 'UTF-8'),
            digestmod=hashlib.sha256
        ).digest()
        self.validation_token = base64.urlsafe_b64encode(dk).decode()

    def format_last_name(self):
        self.last_name = self.last_name.upper()

    def clean(self):
        self.generate_username()
        self.generate_token()
        self.format_last_name()
        return super(PendingUser, self).clean()

    def get_absolute_url(self):
        return reverse('accounts:registration-complete')

    def __str__(self):
        return '{first_name} {last_name} ({username})'.format(
            first_name=self.first_name,
            last_name=self.last_name,
            username=self.username,
        )


class Account(models.Model):
    """
    Account model where you can store all the information about a member.
    From an User object (which you can get easily thanks to Django), you can
    access the related Account entry by `user.account`
    """
    user = models.OneToOneField(
        User,
        verbose_name='default_user',
        on_delete=models.CASCADE,
    )

    cleaning = models.BooleanField(default=True)

    has_paid_membership = models.BooleanField(default=False)

    def __str__(self):
        return '{} {} ({})'.format(
                self.user.first_name,
                self.user.last_name,
                self.user.username)

accounts/views/profile.py
from django import forms
from django.core.urlresolvers import reverse_lazy
from django.contrib import messages
from django.contrib.auth.mixins import LoginRequiredMixin
from django.views import generic
from django.views.generic.edit import UpdateView

from ..ldap.actions import LDAPAccountUpdater
from ..ldap.utils import test_user_bind
from ..models import Account


class UpdatePasswordForm(forms.Form):
    old_password = forms.CharField(
            widget=forms.PasswordInput(),
            label='Ancien mot de passe')

    new_password = forms.CharField(
            widget=forms.PasswordInput(),
            label='Nouveau mot de passe')

    new_password_conf = forms.CharField(
            widget=forms.PasswordInput(),
            label='Confirmation du mot de passe')


class UpdatePasswordView(LoginRequiredMixin, generic.FormView):
    template_name = 'accounts/update_password.html'
    form_class = UpdatePasswordForm
    success_url = reverse_lazy('accounts:profile')

    def form_valid(self, form):
        old_password = form.cleaned_data['old_password']
        new_password = form.cleaned_data['new_password']
        new_password_conf = form.cleaned_data['new_password_conf']

        if not test_user_bind(
                self.request.user.ldap_user.dn,
                old_password):
            form.add_error(
                    'old_password',
                    'The old password is incorrect')
            return super(UpdatePasswordView, self).form_invalid(form)
        elif new_password != new_password_conf:
            form.add_error(
                    'new_password',
                    'Passwords are not the same')
            return super(UpdatePasswordView, self).form_invalid(form)
        else:
            account_updater = LDAPAccountUpdater(self.request.user.ldap_user.dn)
            if account_updater.change_password(old_password, new_password):
                return super(UpdatePasswordView, self).form_valid(form)
            else:
                form.add_error(
                        'old_password',
                        'Unable to perform update')
                return super(UpdatePasswordView, self).form_invalid(form)


class ProfileView(LoginRequiredMixin, UpdateView):
    template_name = "accounts/profile.html"
    model = Account
    fields = ['cleaning']
    success_url = reverse_lazy('accounts:profile')

    def form_valid(self, form):
        messages.success(self.request, 'Your cleaning preference was successfully updated')
        return super(ProfileView, self).form_valid(form)

    def get_object(self, queryset=None):
        return self.request.user.account

accounts/views/registration.py
from captcha.fields import CaptchaField

from django import forms
from django.conf import settings
from django.core.mail import send_mail
from django.template import loader
from django.views import generic

from ..models import PendingUser


class RegisterForm(forms.ModelForm):
    agreement = forms.BooleanField()
    captcha = CaptchaField()

    class Meta:
        model = PendingUser
        fields = ['first_name', 'last_name', 'email']


class RegisterView(generic.edit.CreateView):
    template_name = 'accounts/register.html'
    model = PendingUser
    form_class = RegisterForm

    def render_mail_content(self, pending_user):
        template = loader.get_template('accounts/validation_mail.html')

        url_prefix = 'https://' if settings.PLATFORM_USING_HTTPS else 'http://'
        platform_url = url_prefix + settings.PLATFORM_HOSTNAME

        context = {
            'first_name': pending_user.first_name,
            'last_name': pending_user.last_name,
            'email': pending_user.email,
            'username': pending_user.username,
            'platform_url': platform_url,
            'validation_token': pending_user.validation_token,
            'PLATFORM_NAME': settings.PLATFORM_NAME,
        }

        return template.render(context, self.request)

    def form_valid(self, form):
        '''Validate the account informations and send a confirmation mail.'''
        pending_user = form.save(commit=False)

        # Send confirmation email
        send_mail(
            'Account validation',
            self.render_mail_content(pending_user),
            settings.MAIL_SENDER,
            [pending_user.email],
        )

        return super(RegisterView, self).form_valid(form)


class RegistrationCompleteView(generic.TemplateView):
    template_name = 'accounts/registration_complete.html'

accounts/views/validation.py
from django import forms
from django.core.urlresolvers import reverse_lazy
from django.forms import ValidationError
from django.shortcuts import get_object_or_404
from django.views import generic

from ..models import PendingUser
from ..ldap.actions import LDAPAccountAdder


class ValidateRegistrationForm(forms.Form):
    password = forms.CharField(widget=forms.PasswordInput())
    password_conf = forms.CharField(widget=forms.PasswordInput())


class ValidateRegistrationView(generic.FormView):
    '''Try to find the DB entry corresponding to the given token
    if one entry is found, ask for a password and sync the account
    with the LDAP.'''

    template_name = 'accounts/finish_validation.html'
    form_class = ValidateRegistrationForm
    success_url = reverse_lazy('accounts:validation-complete')

    def load_pending_user(self, token):
        self.pending_user = get_object_or_404(
            PendingUser,
            validation_token=token,
        )

    def get(self, *args, **kwargs):
        self.load_pending_user(kwargs['token'])
        return super(ValidateRegistrationView, self).get(self, *args, **kwargs)

    def form_valid(self, form):
        self.load_pending_user(self.kwargs['token'])

        password = form.cleaned_data['password']
        password_conf = form.cleaned_data['password_conf']

        try:
            if password != password_conf:
                raise ValidationError(
                    'Passwords are not the same',
                    code='invalid',
                )
            elif LDAPAccountAdder().add(
                    self.pending_user,
                    form.cleaned_data['password']):
                self.pending_user.delete()
                return super(ValidateRegistrationView, self).form_valid(form)
            else:
                raise ValidationError(
                        'Duplicate UID or CN, please contact an administrator',
                        code='invalid',
                    )
        except ValidationError as e:
            form.add_error(None, str(e))
            return super(ValidateRegistrationView, self).form_invalid(form)


class ValidationCompleteView(generic.TemplateView):
    template_name = 'accounts/validation_complete.html'

accounts/templates/accounts/finish_validation.html
{% extends "base_accounts.html" %}
{% block title %}
	Finaliser la validation
{% endblock %}

{% block main %}
<div class="row">
	<h4>Encore une étape ...</h4>
	Pour finaliser votre inscription, merci de fournir un mot de passe pour
	votre compte :
	<form action="" method="post">
		{% csrf_token %}
		{{ form.as_p }}
		<input type="submit" value="Envoyer" class="btn" />
	</form>
</div>
{% endblock %}

accounts/templates/accounts/profile.html
{% extends "base_accounts.html" %}
{% block title %}
  Mon compte
{% endblock %}

{% block main %}

<div class="row">
  <h4>Profil</h4>
  <p>
    Sur votre page de profil, vous pouvez modifier les différents paramètres
    concernant votre inscription à ATILLA
  </p>
  <form action="" method="post">
    {% csrf_token %}
    {{ form.non_field_errors }}
    <p>
      {{ form.cleaning }}
      <label for="{{ form.cleaning.id_for_label }}">
        Je veux bien aider au ménage de la CY106 (sélection aléatoire toutes
        les semaines)
      </label>
    </p>
    <input type="submit" value="Envoyer" class="btn" />
  </form>
  <br/>
  <a class="waves-effect waves-light btn" href="{% url "accounts:change_password" %}">
    Changer le mot de passe
  </a>
</div>
{% endblock %}

accounts/templates/accounts/register.html
{% extends "base_accounts.html" %}
{% block title %}
	Inscription
{% endblock %}

{% block main %}
<div class="row">
	<h4>Inscription</h4>
	<p>
		L’inscription à {{ PLATFORM_NAME }} vous permet d’accéder à de
		nombreux services de notre association.
	</p>
	<form action="" method="post">
		{% csrf_token %}
		{{ form.non_field_errors }}
		<p>
			<label for="{{ form.first_name.id_for_label }}">
					First name&nbsp;:
			</label>
			{{ form.first_name }}
		</p>
		<p>
			<label for="{{ form.last_name.id_for_label }}">
					Last name&nbsp;:
			</label>
			{{ form.last_name }}
		</p>
		<p>
			<label for="{{ form.email.id_for_label }}">
					E-Mail&nbsp;:
			</label>
			{{ form.email }}
		</p>
		<p>
			<label for="{{ form.captcha.id_for_label }}">
					Êtes vous un humain&nbsp;?
			</label>
			<br/>
			{{ form.captcha }}
		<p>
			{{ form.agreement }}
			<label for="{{ form.agreement.id_for_label }}">
					En cochant cette case, je certifie être membre d’ATILLA, avoir accepté la charte
					d'utilisation des ressources informatiques de l'EISTI et accepter le stockage
					de données personnelles (<a target="_blank" href="{% url 'legal' %}">plus d'informations</a>)
			</label>
		</p>
		<input type="submit" value="Envoyer" class="btn" />
	</form>
</div>
{% endblock %}

accounts/templates/accounts/registration_complete.html
{% extends "base_accounts.html" %}
{% block title %}
	Enregistrement terminé
{% endblock %}

{% block main %}
<div class="row valign-wrapper green-text text-darken-1">
	<div class="col s1 offset-s4 center-align">
		<i class="large material-icons center-align">done</i>
	</div>
	<div class="col s7">
		<h4 class="valign">Enregistrement terminé !</h4>
	</div>
</div>
<div class="row">
	<p class="center-align">
		Un e-mail de validation vous a été envoyé ; merci de cliquer sur le
		lien de confirmation dans ce dernier pour finaliser la création de
		votre compte.
	</p>
</div>
{% endblock %}

accounts/templates/accounts/update_password.html
{% extends "base_accounts.html" %}
{% block title %}
	Modification du mot de passe
{% endblock %}

{% block main %}
<div class="row">
	<h4>Modification du mot de passe</h4>
	<form action="" method="post">
		{% csrf_token %}
		{{ form.as_p }}
		<input type="submit" value="Envoyer" class="btn" />
	</form>
</div>
{% endblock %}

accounts/templates/accounts/validation_complete.html
{% extends "base_accounts.html" %}
{% block title %}
	Validation terminée
{% endblock %}


{% block main %}
<div class="row valign-wrapper green-text text-darken-1">
	<div class="col s1 offset-s4 center-align">
		<i class="large material-icons center-align">done</i>
	</div>
	<div class="col s7">
		<h4 class="valign">Validation terminée !</h4>
	</div>
</div>
<div class="row">
	<p class="center-align">
		Merci d’avoir validé votre compte ! <br/>
		Vous pouvez dès à présent vous connecter à la plateforme ainsi
		qu’aux autres services fournis par
		<span class="orange-text text-darken-4">>~/ATILLA</span>.
	</p>
</div>
{% endblock %}

accounts/templates/accounts/validation_mail.html
Bonjour {{ first_name }},

Votre login pour la plateforme {{ PLATFORM_NAME }} est : {{ username }}

Pour finaliser votre inscription sur {{ PLATFORM_NAME }}, merci de suivre le
lien ci-après :

{{ platform_url }}{% url 'accounts:validate' validation_token %}

A très bientôt !