accounts/urls.py
from django.conf.urls import url
from django.contrib.auth import views as auth_views
from .views import registration, validation, profile

app_name = "accounts"
urlpatterns = [
    url('^login/$', auth_views.login, name='login'),
    url('^logout/$', auth_views.logout, name='logout'),
    url('^register/$', registration.RegisterView.as_view(), name='register'),
    url('^register/complete/$',
        registration.RegistrationCompleteView.as_view(),
        name='registration-complete'),
    url('^validate/complete/$',
        validation.ValidationCompleteView.as_view(),
        name='validation-complete'),
    url('^validate/token/(?P<token>.*)',
        validation.ValidateRegistrationView.as_view(),
        name='validate'),
    url('^password/update/$',
        profile.UpdatePasswordView.as_view(),
        name='change_password'),
    url('^', profile.ProfileView.as_view(), name='profile'),
]

cleaning/urls.py
from django.conf.urls import url
from . import views
app_name = "cleaning"
urlpatterns = [
    url('^', views.portal_view, name="portal"),
]

ethernet_auth/urls.py
from django.conf.urls import url

from .views import SwitchPortView
from .views import SwitchPortDetailView
from .views import SwitchPortActionCreateView

app_name = 'ethernet_auth'

urlpatterns = [
    url(r'^switches/ports/$', SwitchPortView.as_view(), name='switch_port_list'),
    url(r'^switches/ports/(?P<pk>[0-9]+)/$', SwitchPortDetailView.as_view(), name='switch_port_detail'),
    url(r'^switches/ports/(?P<pk>[0-9]+)/actions/add/$', SwitchPortActionCreateView.as_view(),
        name='switch_port_action_create')
]

members/urls.py
from django.conf.urls import include, url
from django.contrib import admin

from network.views import device
from members.views import legal_view

urlpatterns = [
    url(r'^legal$', legal_view, name="legal"),
    url(r'^admin/', admin.site.urls),
    url(
        r'^accounts/',
        include('accounts.urls', namespace='accounts'),
    ),
    url(r'^captcha/', include('captcha.urls')),
    url(r'^network/', include('network.urls')),
    url(r'^cleaning/', include('cleaning.urls')),
    url(r'^ethernet/', include('ethernet_auth.urls')),
    url(r'^$', device.DeviceView.as_view(), name="portal")
]

network/urls.py
from django.conf.urls import url

from .views import device, interface, render

app_name = 'network'

urlpatterns = [
    url(r'^devices/$',
        device.DeviceView.as_view(),
        name='index'),
    url(r'^devices/add/$',
        device.DeviceCreateView.as_view(),
        name='device_create'),
    url(r'^devices/(?P<pk>[0-9]+)/$',
        device.DeviceDetailView.as_view(),
        name='device_detail'),
    url(r'^devices/(?P<pk>[0-9]+)/edit/$',
        device.DeviceUpdateView.as_view(),
        name='device_update'),
    url(r'^devices/(?P<pk>[0-9]+)/delete/$',
        device.DeviceDeleteView.as_view(),
        name='device_delete'),

    url(r'^devices/(?P<pk>[0-9]+)/interfaces/add/$',
        interface.InterfaceCreateView.as_view(),
        name='interface_create'),
    url(r'^devices/(?P<pk1>[0-9]+)/interfaces/(?P<pk2>[0-9]+)/edit/$',
        interface.InterfaceUpdateView.as_view(),
        name='interface_update'),
    url(r'^devices/(?P<pk1>[0-9]+)/interfaces/(?P<pk2>[0-9]+)/delete/$',
        interface.InterfaceDeleteView.as_view(),
        name='interface_delete'),

    url(r'^render/dhcp/$',
        render.RenderDHCPView.as_view(),
        name='render_DHCP'),
    url(r'^render/dns/$',
        render.RenderDNSView.as_view(),
        name='render_DNS'),
    url(r'^render/dns/reverse/$',
        render.RenderReverseDNSView.as_view(),
        name='render_reverse_DNS'),
]

templates/base.html
{# I thied to respect the 80-chars rule … #}
{% load compress %}
{% load staticfiles %}
<!DOCTYPE html>
<html>
	<head>
		<meta charset="UTF-8"/>

		{% compress css %}
		<link type="text/scss"
			rel="stylesheet"
			href="{% static "sass/materialize.scss" %}"
			media="screen,projection"/>
		<link type="text/scss"
			rel="stylesheet"
			href="{% static "sass/base.scss" %}"
			media="screen,projection"/>
		{% endcompress %}

		<meta name="viewport"
			content="width=device-width, initial-scale=1.0"/>

		<title>
			{% block title %}
			{% endblock %}
			| members.atilla.org
		</title>

		<link type="text/css" rel="stylesheet"
			 href="{% static "fonts/material/material-icons.css" %}"/>

		<style type="text/css">
		@font-face {
			   font-family: 'Material Icons';
			   font-style: normal;
			   font-weight: 400;
			   src: url({% static "fonts/material/MaterialIcons-Regular.eot" %});
			   src: local('Material Icons'),
				   local('MaterialIcons-Regular'),
				   url({% static "fonts/material/MaterialIcons-Regular.woff2" %})
				        format('woff2'),
				   url({% static "fonts/material/MaterialIcons-Regular.woff" %})
				        format('woff'),
				   url({% static "MaterialIcons-Regular.ttf" %}) format('truetype');
		}
		</style>

		<!-- Piwik -->
		<script type="text/javascript">
			var _paq = _paq || [];
			_paq.push(['trackPageView']);
			_paq.push(['enableLinkTracking']);
			(function() {
				var u="//piwik.atilla.org/";
				_paq.push(['setTrackerUrl', u+'piwik.php']);
				_paq.push(['setSiteId', '3']);
				var d=document,
					g=d.createElement('script'),
					s=d.getElementsByTagName('script')[0];
				g.type='text/javascript';
				g.async=true;
				g.defer=true;
				g.src=u+'piwik.js';
				s.parentNode.insertBefore(g,s);
			})();
		</script>
		<noscript><p><img src="//piwik.atilla.org/piwik.php?idsite=3" style="border:0;" alt="" /></p></noscript>
		<!-- End Piwik Code -->
	</head>
	<body>
		<header>
			<nav>
				<div class="nav-wrapper">
					<a href="#" data-activates="mobile-demo"
						class="button-collapse left">
						   <i class="material-icons">menu</i>
					</a>
          <a href="{% url "portal" %}"
						class="brand-logo center">
						>~/ATILLA
					</a>
					{% if request.user.is_authenticated %}
					<ul class="left hide-on-med-and-down">
						<li>
							<a href="{% url "accounts:profile" %}">
								Mon compte
							</a>
            </li>
            <li>
							<a href="{% url "network:index" %}">
								Réseau
							</a>
						</li>
            <li>
              <a href="{% url "cleaning:portal" %}">
                Ménage
              </a>
            </li>
					</ul>
					{% endif %}
					<ul class="right hide-on-med-and-down">
						<li>
						{% if request.user.is_authenticated %}
							<a href="{% url "accounts:logout" %}">
								Déconnexion
							</a>
						{% else %}
							<a href="{% url "accounts:login" %}">
								Connexion
							</a>
							<a href="{% url "accounts:register" %}">
								Inscription
							</a>
						{% endif %}
						</li>
					</ul>

					<ul class="side-nav" id="mobile-demo">
						{% if request.user.is_authenticated %}
						     <li><a href="{% url "accounts:profile" %}">Mon compte</a></li>
						     <li><a href="{% url "network:index" %}">Réseau</a></li>
						     <li><a href="{% url "cleaning:portal" %}">Ménage</a></li>
						     <li><a href="{% url "accounts:logout" %}">Déconnexion</a></li>
						{% else %}
						     <li><a href="{% url "accounts:login" %}">Connexion</a></li>
						     <li><a href="{% url "accounts:register" %}">Inscription</a></li>
						{% endif %}
					</ul>
				</div>
			</nav>
		</header>
		<main>
			<div class="row">
				<div class="col m8 offset-m2">
					{% block main %}
					{% endblock %}
				</div>
			</div>
		</main>
		<footer class="page-footer">
			<div class="container">
				<div class="row">
					Fait avec amour par l’association >~/ATILLA
				</div>
			</div>
		</footer>
		<div id="scripts">
			<script type="text/javascript"
				src="{% static "js/jquery-2.1.1.min.js" %}">
			</script>
			<script type="text/javascript"
	   			src="{% static "js/materialize.min.js" %}">
			</script>
			<script type="text/javascript"
				src="{% static "js/custom.js" %}">
			</script>
			{% block scripts %}
			{% endblock %}
		</div>
	</body>
</html>

templates/base_errors.html
{% extends "base.html" %}

{% block main %}

<h1>{% block errorTitle %}{% endblock %}</h1>

<p>{% block errorDescription %}{% endblock %}</p>

<p>Si vous pensez qu’il s’agit d’un problème, n’hésitez pas à nous en faire part en envoyant un mail à <a href="mailto:bureau@lists.atilla.org">bureau@lists.atilla.org</a>.</p>

<h3>Informations détaillées</h3>

{% if request_path %}
     <h4>Adresse de la requête : </h4>
     <pre>{{ request_path }}</pre>
{% endif %}

{% if exception %}
     <h4>Message d’erreur : </h4>
     <pre>{{ exception }}</pre>
{% endif %}

{% endblock %}

templates/legal.html
{% extends "base.html" %}
{% block title %}Légal{% endblock %}

{% block main %}

<h1>Données personnelles</h1>

<p>Les informations recueillies à partir de cette plateforme font l’objet d’un traitement informatique destiné exclusivement à
ATILLA, pour la finalité suivante : Gestion des membres et des accès au réseau ATILLA.</p>

<p>Les données récoltées sont exclusivement dédiées aux membres du bureau d'ATILLA.</p>

<p>Conformément à la loi « informatique et libertés » du 6 janvier 1978 modifiée, vous disposez d’un droit d’accès et de rectification aux informations qui vous concernent.
Vous pouvez accèder aux informations vous concernant en vous adressant aux membres du bureau (<a href="mailto:bureau@lists.atilla.org">bureau@lists.atilla.org</a>).</p>

<p>Vous pouvez également, pour des motifs légitimes, vous opposer au traitement des données vous concernant.
Pour en savoir plus, consultez vos droits sur le site de la CNIL.</p>
{% endblock %}